# Generated by Django 4.0.1 on 2022-09-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSubChapter', models.BooleanField(default=False)),
                ('isHeading', models.BooleanField(default=False)),
                ('isSubHeading', models.BooleanField(default=False)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('headingCode', models.CharField(blank=True, max_length=512, null=True)),
                ('subheadingCode', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('unitOfQty', models.CharField(blank=True, max_length=512, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orderRank', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'TariffDetail',
                'verbose_name_plural': 'TariffDetails',
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('appliedGir', models.CharField(max_length=512, null=True)),
                ('considerationStep', models.TextField(max_length=512)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orderRank', models.PositiveIntegerField(null=True)),
                ('remarks', models.TextField(blank=True, max_length=512, null=True)),
                ('tariff_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.tariffdetail', verbose_name='Subheading')),
            ],
            options={
                'verbose_name': 'Guideline',
                'verbose_name_plural': 'Guideline',
            },
        ),
    ]
