# Generated by Django 4.0.1 on 2022-09-04 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_tariffdetail_alter_album_id_alter_song_id_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tariff_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.tariffdetail', verbose_name='Subheading'),
        ),
    ]
