# Generated by Django 4.0.1 on 2022-09-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_item_tariff_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffdetail',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tariffdetail',
            name='headingCode',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
